# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d26223543e084ddf42c3aed84f458d7b1fa534a8d4e8514b48eb31d7a4995f29709868d4b34868d204e7c1c0b2c8df003ff3851eddd4bdc8076e9f17a24d6f7

test:
  secret_key_base: b582e8f40f336b24a00836bf6f65ed9485cbbbda688d04e92b35bd5a1c28e276c4593390bf4b317aea11337f7cd1766a1aab91e21191bde8e8da32178bcde656

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
